module Main where

import Text.Pandoc.JSON

main :: IO ()
main = toJSONFilter unicodeToLatex

unicodeToLatex :: Inline -> Inline
unicodeToLatex (Math t e) = Math t (concatMap sym e)
unicodeToLatex x          = x

sym :: Char -> String
sym '¬' = "\\neg"
sym '±' = "\\pm"
sym '×' = "\\times"
sym '÷' = "\\div"
sym '…' = "\\dots"
sym '←' = "\\leftarrow"
sym '↑' = "\\uparrow"
sym '→' = "\\rightarrow"
sym '↓' = "\\downarrow"
sym '↔' = "\\leftrightarrow"
sym '⇒' = "\\Rightarrow"
sym '⇔' = "\\Leftrightarrow"
sym '∀' = "\\forall"
sym '∃' = "\\exists"
sym '∅' = "\\emptyset"
sym '∈' = "\\in"
sym '∉' = "\\notin"
sym '∋' = "\\ni"
sym '∎' = "\\blacksquare"
sym '∑' = "\\sum"
sym '∓' = "\\mp"
sym '∗' = "\\ast"
sym '∘' = "\\circ"
sym '∙' = "\\bullet"
sym '∝' = "\\propto"
sym '∞' = "\\infty"
sym '∥' = "\\parallel"
sym '∧' = "\\land"
sym '∨' = "\\lor"
sym '∩' = "\\cap"
sym '∪' = "\\cup"
sym '∴' = "\\therefore"
sym '∵' = "\\because"
sym '≠' = "\\neq"
sym '≡' = "\\equiv"
sym '≤' = "\\leq"
sym '≥' = "\\geq"
sym '⊂' = "\\subset"
sym '⊃' = "\\supset"
sym '⊆' = "\\subseteq"
sym '⊇' = "\\supseteq"
sym '⊢' = "\\vdash"
sym '⊤' = "\\top"
sym '⊥' = "\\bot"
sym '⊨' = "\\vDash"
sym '⋅' = "\\cdot"
sym '⋮' = "\\vdots"
sym '⋯' = "\\cdots"
sym 'α' = "\\alpha"
sym 'Α' = "A"
sym 'β' = "\\beta"
sym 'Β' = "B"
sym 'γ' = "\\gamma"
sym 'Γ' = "\\Gamma"
sym 'δ' = "\\delta"
sym 'Δ' = "\\Delta"
sym 'ε' = "\\epsilon"
sym 'Ε' = "E"
sym 'ζ' = "\\zeta"
sym 'Ζ' = "Z"
sym 'η' = "\\eta"
sym 'Η' = "H"
sym 'θ' = "\\theta"
sym 'Θ' = "\\Theta"
sym 'ι' = "\\iota"
sym 'Ι' = "I"
sym 'κ' = "\\kappa"
sym 'Κ' = "K"
sym 'λ' = "\\lambda"
sym 'Λ' = "\\Lambda"
sym 'μ' = "\\mu"
sym 'Μ' = "M"
sym 'ν' = "\\nu"
sym 'Ν' = "N"
sym 'ξ' = "\\xi"
sym 'Ξ' = "\\Xi"
sym 'ο' = "o"
sym 'Ο' = "O"
sym 'π' = "\\pi"
sym 'Π' = "\\Pi"
sym 'ρ' = "\\rho"
sym 'Ρ' = "P"
sym 'σ' = "\\sigma"
sym 'Σ' = "\\Sigma"
sym 'τ' = "\\tau"
sym 'Τ' = "T"
sym 'υ' = "\\upsilon"
sym 'Υ' = "\\Upsilon"
sym 'φ' = "\\phi"
sym 'Φ' = "\\Phi"
sym 'χ' = "\\chi"
sym 'Χ' = "X"
sym 'ψ' = "\\psi"
sym 'Ψ' = "\\Psi"
sym 'ω' = "\\omega"
sym 'Ω' = "\\Omega"
sym  s  = [s]

-- TODO \varepsilon
-- TODO \vartheta
-- TODO \varrho
-- TODO \varphi
