module Main where

import Text.Pandoc.JSON

main :: IO ()
main = toJSONFilter unicodeToLatex

unicodeToLatex :: Inline -> Inline
unicodeToLatex (Math t e) = Math t (concatMap symbols e)
unicodeToLatex x          = x

symbols :: Char -> String
symbols '¬' = "\\neg"
symbols '±' = "\\pm"
symbols '×' = "\\times"
symbols '÷' = "\\div"
symbols '…' = "\\dots"
symbols '←' = "\\leftarrow"
symbols '↑' = "\\uparrow"
symbols '→' = "\\rightarrow"
symbols '↓' = "\\downarrow"
symbols '↔' = "\\leftrightarrow"
symbols '⇒' = "\\Rightarrow"
symbols '⇔' = "\\Leftrightarrow"
symbols '∀' = "\\forall"
symbols '∃' = "\\exists"
symbols '∅' = "\\emptyset"
symbols '∈' = "\\in"
symbols '∉' = "\\notin"
symbols '∋' = "\\ni"
symbols '∎' = "\\blacksquare"
symbols '∑' = "\\sum"
symbols '∓' = "\\mp"
symbols '∗' = "\\ast"
symbols '∘' = "\\circ"
symbols '∙' = "\\bullet"
symbols '∝' = "\\propto"
symbols '∞' = "\\infty"
symbols '∥' = "\\parallel"
symbols '∧' = "\\land"
symbols '∨' = "\\lor"
symbols '∩' = "\\cap"
symbols '∪' = "\\cup"
symbols '∴' = "\\therefore"
symbols '∵' = "\\because"
symbols '≠' = "\\neq"
symbols '≡' = "\\equiv"
symbols '≤' = "\\leq"
symbols '≥' = "\\geq"
symbols '⊂' = "\\subset"
symbols '⊃' = "\\supset"
symbols '⊆' = "\\subseteq"
symbols '⊇' = "\\supseteq"
symbols '⊢' = "\\vdash"
symbols '⊤' = "\\top"
symbols '⊥' = "\\bot"
symbols '⊨' = "\\vDash"
symbols '⋅' = "\\cdot"
symbols '⋮' = "\\vdots"
symbols '⋯' = "\\cdots"
symbols 'α' = "\\alpha"
symbols 'Α' = "A"
symbols 'β' = "\\beta"
symbols 'Β' = "B"
symbols 'γ' = "\\gamma"
symbols 'Γ' = "\\Gamma"
symbols 'δ' = "\\delta"
symbols 'Δ' = "\\Delta"
symbols 'ε' = "\\epsilon"
symbols 'Ε' = "E"
symbols 'ζ' = "\\zeta"
symbols 'Ζ' = "Z"
symbols 'η' = "\\eta"
symbols 'Η' = "H"
symbols 'θ' = "\\theta"
symbols 'Θ' = "\\Theta"
symbols 'ι' = "\\iota"
symbols 'Ι' = "I"
symbols 'κ' = "\\kappa"
symbols 'Κ' = "K"
symbols 'λ' = "\\lambda"
symbols 'Λ' = "\\Lambda"
symbols 'μ' = "\\mu"
symbols 'Μ' = "M"
symbols 'ν' = "\\nu"
symbols 'Ν' = "N"
symbols 'ξ' = "\\xi"
symbols 'Ξ' = "\\Xi"
symbols 'ο' = "o"
symbols 'Ο' = "O"
symbols 'π' = "\\pi"
symbols 'Π' = "\\Pi"
symbols 'ρ' = "\\rho"
symbols 'Ρ' = "P"
symbols 'σ' = "\\sigma"
symbols 'Σ' = "\\Sigma"
symbols 'τ' = "\\tau"
symbols 'Τ' = "T"
symbols 'υ' = "\\upsilon"
symbols 'Υ' = "\\Upsilon"
symbols 'φ' = "\\phi"
symbols 'Φ' = "\\Phi"
symbols 'χ' = "\\chi"
symbols 'Χ' = "X"
symbols 'ψ' = "\\psi"
symbols 'Ψ' = "\\Psi"
symbols 'ω' = "\\omega"
symbols 'Ω' = "\\Omega"
symbols  s  = [s]

-- TODO \varepsilon
-- TODO \vartheta
-- TODO \varrho
-- TODO \varphi
