name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}, ghc ${{ matrix.ghc }}, pandoc-types ${{ matrix.pandoc-types }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ["9.0.1"]
        cabal: ["3.4"]
        pandoc-types: ["1.21", "1.22"]
        include:
          # Apparently pandoc-types 1.20 does not work with GHC 9, so use GHC 8,
          # but that is not available on GitHub's Windows hosts.
          - os: [ubuntu-latest, macOS-latest]
            ghc: "8.10.7"
            pandoc-types: "1.20"
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal install --installdir bin --constraint 'pandoc-types==${{ matrix.pandoc-types }}'
      - uses: actions/upload-artifact@v2
        with:
          name: pandoc-unicode-math_${{ runner.os }}_pandoc-types-${{ matrix.pandoc-types }}
          path: ./bin
